# Generated by Django 4.0.6 on 2022-07-22 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_apply_jobpostactivity_apply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='in_recruitment_progress',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='interview_planned',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='submitted',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='under_review',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='writing',
        ),
    ]
